name: Continuous Integration

# Trigger the workflow on push or pull request to the main or develop branch
on:
  push:
    branches: [ '**' ] #for all branches
  pull_request:
    branches: [ main ]

# Define the jobs to run
jobs:
  test:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Steps to execute in this job
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
          cache: 'npm' 

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --omit=optional
      - name: Install test-specific dependencies
        working-directory: ./backend
        run: npm install --save-dev @babel/preset-env @babel/core babel-jest
      # Step 4: Run tests
      - name: Run tests
        working-directory: ./backend
        run: npm test
        env:
          # Provide environment variables for testing
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          NODE_ENV: test


     
     